### PR TITLE
DRAFT: convert to vue composition with ts. add types.

### PR DESCRIPTION
**Pull request by 209**
convert to vue composition. add types.

## Motivation and Context
Becose in 2023 we need types.

## How Has This Been Tested?
Not

Need help for prod-ready)
I've changed initialization plugin.

### CODE REVIEW

**Comment by 209** [comment]
I've converted, but.. project hasn't been worked.
Need help)

**Comment by jhrncar** [comment]
Hi, i am using this package in my bacchelor's thesis and I need types. is this PR working? is there any chance i could get it withou merging? cause as i look at this repo, it seems the cretor doesn't interact

**Comment by 209** [comment]
@jhrncar Hi, I've stabled this PR: all is ok, I think.
package: https://www.npmjs.com/package/@i209/vue3-openlayers
You need add components.d.ts to tsconfig inlude for get declaring global imports. 

build types: It's no the best realisation. I haven't enoght experience to make a excellent build. 

Troubles: default example in repo has low performace. 
Some of features works bad. 
I haven't found a reason, sorry. You can try remove different parts of App.vue template and find problem part.
But my realistic examples work similar as original. 

If you want, you can send me PR with updates/fixes/chages.

I don't want to support my PR long time alone. 
The convert work to ts + composables was realy boring. And more points haven't described enough.
I hope the author will return =) I haven't enough experience in original OpelLayer lib.

**Comment by 209** [comment]
I've rebased PR.

**Comment by d-koppenhagen** [comment]
@209 do you still need help? Would you mind to rebase this PR again?

**Comment by 209** [comment]
> @209 do you still need help? Would you mind to rebase this PR again?

I spent 2 weeks doing a boring job that no one gives a shit about.
I'm sorry, but the main branch has gone too far ahead.

I am not ready to spend 4-8 hours on a rebase if there is no guarantee that someone will consider my branch.
Now we need to review each changed file, evaluate the changes and implement them very carefully.

**Comment by d-koppenhagen** [comment]
@209 i understand your frustration.
I am personally very interested in this change an I think your PR is a great win for stehe project which makes it way more modern!
Big kudos for all your effort.

I recently got a maintainer for this project. I can tell you I would like to bring this PR to production, once it's ready.

I will also try to support you with the work of rebasing (hopefully I will find some time within the next days).

**Comment by d-koppenhagen** [comment]
Hey @209 thanks for all the time you invested which wasn't waste. Meanwhile I picked a lot of TS migrations from your branch and migrated the codebase step-by-step to typescript and script setup. Please checkout the lastest releases (1.0.0-alpha.7 and probably above). 
Once 1.0.0 is stable I will definitely add you to the release notes.
Nonetheless, this PR can be closed, as it's obsolete now.

**Pull request closed without merging**
