### PR TITLE
allow multiple plugin installation

### PR DESCRIPTION
**Pull request by lukas-zaugg**
## Types of Changes

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Other (Tooling, Dependency Updates, etc.)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

If you added a new component feature (layer, geom, source, etc.), please be sure to update the documentation:

- [ ] Add component to `output.globals` in `vite.config.ts`
- [ ] Create a `src/demos/<Component>Demo.vue`
- [ ] Create a `docs/componentsguide/<Category>/<Feature>/index.md` containing the Demo and documentation for the component
- [ ] Add the docs page to `docs/.vitepress/config.ts`
- [ ] Update the sitemap `docs/public/sitemap.xml`

### CODE REVIEW

**Comment by d-koppenhagen** [comment]
Just to understand the problem with the current implementation: what's a reason to install one of the plugins multiple times?

**Comment by lukas-zaugg** [comment]
@d-koppenhagen Our webapp consists of multiple vue apps existing in parallel on the same site. They all use maps and are designed as different apps because we individually reuse them in other places. In my opinion this is not an antipattern:
[multiple-application-instances](https://vuejs.org/guide/essentials/application.html#multiple-application-instances)
What do you think?

**Comment by d-koppenhagen** [comment]
I agree! This should be fine totally. Thanks for your contribution!

**Comment by lukas-zaugg** [comment]
@d-koppenhagen Thanks for maintaining this awesome repo!

**Pull request merged**
